name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      

      
      - name: Install frontend dependencies
        run: npm ci
      
      - name: Check TypeScript
        run: npx tsc --noEmit
      
      - name: Lint frontend
        run: npm run lint
        continue-on-error: true
      
      - name: Check Rust formatting
        run: cd src-tauri && cargo fmt --all -- --check
      
      - name: Run Clippy
        run: cd src-tauri && cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Build frontend
        run: npm run build
      
      - name: Build Rust (check compilation)
        run: cd src-tauri && cargo build