name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Polish Language ${{ github.ref_name }}'
          releaseBody: |
            ## What's Changed
            
            ### Features
            - Text polishing with AI (OpenAI/Gemini)
            - Translation to English
            - Configurable global shortcuts
            - System notifications and sound feedback
            - Menu bar integration
            
            ### Installation
            - **macOS**: Download the `.dmg` file and install the app
            
            ### Default Shortcuts
            - **Polish text**: `Cmd+Option+P`
            - **Translate text**: `Cmd+Option+T`
            
            See the [README](https://github.com/${{ github.repository }}/blob/main/README.md) for setup instructions.
          releaseDraft: false
          prerelease: false